In [1]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.18.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: numpy>=1.16.2 in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (3.3.2)
Requirement already satisfied: setuptools in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (50.3.1.post20201107)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (0.23.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (0.17.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (1.1.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\akhil\anaconda3\lib\site-packages (from mlxtend) (1.4.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\akhil\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in c:\users\akhil\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.0.1)
Requirement already satisfied: cycler>=0.10 in c:\users\akhil\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\akhil\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\akhil\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\akhil\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2020.6.20)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\akhil\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\akhil\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: six in c:\users\akhil\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.18.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [3]:
df = pd.read_csv("C:/Users/Akhil/Desktop/ASSIGNMENTS/my_movies.csv")
df.head()

,V1,V2,V3,V4,V5,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,Sixth Sense,LOTR1,Harry Potter1,Green Mile,LOTR2,1,0,1,1,0,1,0,0,0,1
1,Gladiator,Patriot,Braveheart,NaN,NaN,0,1,0,0,1,0,0,0,1,0
2,LOTR1,LOTR2,NaN,NaN,NaN,0,0,1,0,0,1,0,0,0,0
3,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
4,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   V1             10 non-null     object
 1   V2             10 non-null     object
 2   V3             7 non-null      object
 3   V4             2 non-null      object
 4   V5             1 non-null      object
 5   Sixth Sense    10 non-null     int64
 6   Gladiator      10 non-null     int64
 7   LOTR1          10 non-null     int64
 8   Harry Potter1  10 non-null     int64
 9   Patriot        10 non-null     int64
 10  LOTR2          10 non-null     int64
 11  Harry Potter2  10 non-null     int64
 12  LOTR           10 non-null     int64
 13  Braveheart     10 non-null     int64
 14  Green Mile     10 non-null     int64
dtypes: int64(10), object(5)
memory usage: 1.3+ KB

In [5]:
df.shape

(10, 15)

In [6]:
df1 = pd.get_dummies(df)
df1

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile,...,V2_LOTR,V2_LOTR1,V2_LOTR2,V2_Patriot,V3_Braveheart,V3_Gladiator,V3_Harry Potter1,V3_Sixth Sense,V4_Green Mile,V5_LOTR2
0,1,0,1,1,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,1,1
1,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
5,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
6,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
9,1,1,0,0,0,0,0,1,0,1,...,1,0,0,0,0,1,0,0,1,0

In [7]:
frequent = apriori(df1,min_support=0.2,use_colnames=True)
frequent

    support                                           itemsets
0       0.6                                      (Sixth Sense)
1       0.7                                        (Gladiator)
2       0.2                                            (LOTR1)
3       0.2                                    (Harry Potter1)
4       0.6                                          (Patriot)
..      ...                                                ...
76      0.4  (Sixth Sense, Patriot, V3_Sixth Sense, V2_Patr...
77      0.4  (Sixth Sense, V3_Sixth Sense, V2_Patriot, V1_G...
78      0.4  (Sixth Sense, Patriot, V3_Sixth Sense, V2_Patr...
79      0.4  (Patriot, V3_Sixth Sense, V2_Patriot, V1_Gladi...
80      0.4  (Sixth Sense, Patriot, V3_Sixth Sense, V2_Patr...

[81 rows x 2 columns]

In [8]:
rules = association_rules(frequent,metric="lift",min_threshold=0.8)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.4
1,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8
2,(Patriot),(Sixth Sense),0.6,0.6,0.4,0.666667,1.111111,0.04,1.2
3,(Sixth Sense),(Patriot),0.6,0.6,0.4,0.666667,1.111111,0.04,1.2
4,(Sixth Sense),(Green Mile),0.6,0.2,0.2,0.333333,1.666667,0.08,1.2
...,...,...,...,...,...,...,...,...,...
649,(Patriot),"(Sixth Sense, V3_Sixth Sense, V2_Patriot, V1_G...",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8
650,(V3_Sixth Sense),"(Sixth Sense, Patriot, V2_Patriot, V1_Gladiato...",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
651,(V2_Patriot),"(Sixth Sense, Patriot, V3_Sixth Sense, V1_Glad...",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8
652,(V1_Gladiator),"(Sixth Sense, Patriot, V3_Sixth Sense, V2_Patr...",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8
653,(Gladiator),"(Sixth Sense, Patriot, V3_Sixth Sense, V2_Patr...",0.7,0.4,0.4,0.571429,1.428571,0.12,1.4

In [9]:
rules.sort_values("lift",ascending=False)[0:100]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
327,(V4_Green Mile),"(V1_Sixth Sense, Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
89,(V1_Sixth Sense),"(Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
32,(V1_Sixth Sense),(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
33,(Green Mile),(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
321,"(Sixth Sense, Green Mile)","(V1_Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
...,...,...,...,...,...,...,...,...,...
554,"(V3_Sixth Sense, V2_Patriot)","(Patriot, Sixth Sense, V1_Gladiator)",0.4,0.4,0.4,1.0,2.5,0.24,inf
555,"(V3_Sixth Sense, V1_Gladiator)","(Patriot, Sixth Sense, V2_Patriot)",0.4,0.4,0.4,1.0,2.5,0.24,inf
499,(V3_Sixth Sense),"(Patriot, Gladiator, Sixth Sense, V2_Patriot)",0.4,0.4,0.4,1.0,2.5,0.24,inf
495,"(V3_Sixth Sense, Gladiator)","(Patriot, Sixth Sense, V2_Patriot)",0.4,0.4,0.4,1.0,2.5,0.24,inf
494,"(V3_Sixth Sense, V2_Patriot)","(Patriot, Gladiator, Sixth Sense)",0.4,0.4,0.4,1.0,2.5,0.24,inf

In [10]:
rules[rules.lift>3]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
24,(LOTR2),(LOTR1),0.2,0.2,0.2,1.0,5.0,0.16,inf
25,(LOTR1),(LOTR2),0.2,0.2,0.2,1.0,5.0,0.16,inf
32,(V1_Sixth Sense),(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
33,(Green Mile),(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
34,(V4_Green Mile),(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
35,(Green Mile),(V4_Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
40,(V1_Sixth Sense),(V4_Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
41,(V4_Green Mile),(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
86,"(V1_Sixth Sense, Sixth Sense)",(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
88,"(Sixth Sense, Green Mile)",(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
89,(V1_Sixth Sense),"(Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
91,(Green Mile),"(V1_Sixth Sense, Sixth Sense)",0.2,0.2,0.2,1.0,5.0,0.16,inf
92,"(Sixth Sense, V4_Green Mile)",(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
94,"(Sixth Sense, Green Mile)",(V4_Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
95,(V4_Green Mile),"(Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
97,(Green Mile),"(Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
110,"(V1_Sixth Sense, Sixth Sense)",(V4_Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
112,"(Sixth Sense, V4_Green Mile)",(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
113,(V1_Sixth Sense),"(Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
115,(V4_Green Mile),"(V1_Sixth Sense, Sixth Sense)",0.2,0.2,0.2,1.0,5.0,0.16,inf
176,"(V1_Sixth Sense, V4_Green Mile)",(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
177,"(V1_Sixth Sense, Green Mile)",(V4_Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
178,"(V4_Green Mile, Green Mile)",(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
179,(V1_Sixth Sense),"(V4_Green Mile, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
180,(V4_Green Mile),"(V1_Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
181,(Green Mile),"(V1_Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
314,"(V1_Sixth Sense, Sixth Sense, Green Mile)",(V4_Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
315,"(V1_Sixth Sense, Sixth Sense, V4_Green Mile)",(Green Mile),0.2,0.2,0.2,1.0,5.0,0.16,inf
317,"(V4_Green Mile, Sixth Sense, Green Mile)",(V1_Sixth Sense),0.2,0.2,0.2,1.0,5.0,0.16,inf
318,"(V1_Sixth Sense, Sixth Sense)","(V4_Green Mile, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
319,"(V1_Sixth Sense, Green Mile)","(Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
320,"(V1_Sixth Sense, V4_Green Mile)","(Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
321,"(Sixth Sense, Green Mile)","(V1_Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
322,"(Sixth Sense, V4_Green Mile)","(V1_Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
323,"(V4_Green Mile, Green Mile)","(V1_Sixth Sense, Sixth Sense)",0.2,0.2,0.2,1.0,5.0,0.16,inf
324,(V1_Sixth Sense),"(V4_Green Mile, Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
326,(Green Mile),"(V1_Sixth Sense, Sixth Sense, V4_Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf
327,(V4_Green Mile),"(V1_Sixth Sense, Sixth Sense, Green Mile)",0.2,0.2,0.2,1.0,5.0,0.16,inf